DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

baseURL = "https://solnascente.eu/"
languageCode = "en-us"
title = "Sol Nascente"
theme = ["hugo-now-ui"]
staticDir = ["static"]

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
  [languages.pt]
    weight = 2
    languageName = "Portugês"
  [languages.es]
    weight = 3
    languageName = "Español"

[params]
  instagram = "https://instagram.com/test"
  facebook = "https://facebook.com/test"
  twitter = "https://twitter.com/test"
